version: "3.8"
services:
        db:
                image: "mcr.microsoft.com/mssql/server"
                environment:
                        SA_PASSWORD: "Password!"
                        ACCEPT_EULA: "Y"
                ports:
                        - "1433:1433"
                volumes:
                        - /var/opt/mssql/data:/var/opt/mssql/data
        nginx:
                build: ./Nginx
                links:
                        - recipe:recipe
                ports:
                        - "80:80"
        recipe:
                build: .
                ports:
                        - "80"
                depends_on:
                        - db
