FROM microsoft/dotnet:2.0-sdk AS build
COPY RecipeApplication/*.csproj ./app/RecipeApplication/
WORKDIR /app/RecipeApplication
RUN dotnet restore

COPY RecipeApplication/. ./
RUN dotnet publish -o out /p:PublishWithAspNetCoreTargetManifest="false"

FROM microsoft/dotnet:2.0-runtime AS runtime
ENV ASPNETCORE_URLS http://+:80
WORKDIR /app
COPY --from=build /app/RecipeApplication/out ./
ENTRYPOINT ["dotnet", "RecipeApplication.dll"]
